spring:
  application:
    name: SpringBootDemo
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

text:
  content : Hello world!